{% set name = "pyMapVBVD" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce163cd6660894f2d230f7e3e69957ef52ea83913b7054b0cd9af328c25f162f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - attrdict
    - tqdm
    - scipy

test:
  imports:
    - mapvbvd

about:
  home: https://github.com/wexeee/pymapvbvd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of mapVBVD.
  description: |
    Python port of mapVBVD.
  doc_url: https://github.com/wexeee/pymapvbvd
  dev_url: https://github.com/wexeee/pymapvbvd

extra:
  recipe-maintainers:
    - wexeee
